name: CI

on:
  push:
    branches:
      - '**'        # matches every branch
  pull_request:
    branches:
      - '**'        # matches every branch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: JS Code Sniff
        run: docker build . --file docker/prettier/Dockerfile --tag trackr-js-sniff:$(date +%s)