version: '3.9'

services:
  trackr:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
  sniff:
    build:
      context: .
      dockerfile: docker/prettier/Dockerfile
  java-test:
    build:
      context: .
      dockerfile: docker/java-test/Dockerfile
  js-test:
    build:
      context: .
      dockerfile: docker/js-test/Dockerfile