
INSERT INTO USERS(USERNAME, PASSWORD, EMAIL) VALUES ('tflucker', 'password1', 'tflucker@email.com');
INSERT INTO USERS(USERNAME, PASSWORD, EMAIL) VALUES ('jDorancy', 'password2', 'jDorancy@email.com');
INSERT INTO USERS(USERNAME, PASSWORD, EMAIL) VALUES ('xHou', 'password3', 'xHou@email.com');
INSERT INTO USERS(USERNAME, PASSWORD, EMAIL) VALUES ('wLiang', 'password4', 'wLiang@email.com');

INSERT INTO BANK_ACCOUNT(USER_ID, ACCOUNT_TYPE, ACCOUNT_DESCRIPTION, BALANCE, STATUS) VALUES (1, 'SAVINGS', 'Honeymoon Fund', 13291.88, 'ACTIVE');
INSERT INTO BANK_ACCOUNT(USER_ID, ACCOUNT_TYPE, ACCOUNT_DESCRIPTION, BALANCE, STATUS) VALUES (2, 'CHECKING', 'Personal Checking Account', 5810.23, 'ACTIVE');
INSERT INTO BANK_ACCOUNT(USER_ID, ACCOUNT_TYPE, ACCOUNT_DESCRIPTION, BALANCE, STATUS) VALUES (3, 'CHECKING', 'Educational Stipend Account', 928.22, 'ACTIVE');
INSERT INTO BANK_ACCOUNT(USER_ID, ACCOUNT_TYPE, ACCOUNT_DESCRIPTION, BALANCE, STATUS) VALUES (4, 'SAVINGS', 'Gaming PC fund', 800.00, 'ACTIVE');