
CREATE TABLE USERS (
	id int PRIMARY KEY AUTO_INCREMENT,
	first_name VARCHAR(100) NOT NULL,
	last_name VARCHAR(100) NOT NULL,
	username VARCHAR(50) NOT NULL,
	password VARCHAR(100) NOT NULL,
	email VARCHAR(100) NOT NULL
);

CREATE TABLE BANK_ACCOUNTS(
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	user_id BIGINT NOT NULL,
	account_type VARCHAR(50) NOT NULL,
	account_description VARCHAR(255),
	balance BIGINT NOT NULL,
	status VARCHAR(50) NOT NULL
);

CREATE TABLE TRANSACTIONS(
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	bank_account_id BIGINT NOT NULL,
	money BIGINT NOT NULL,
	time VARCHAR(100) NOT NULL,
	counterparty VARCHAR(100) NOT NULL,
	transaction_description VARCHAR(255),
	status VARCHAR(50) NOT NULL
);