
CREATE TABLE USERS (
	id int PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(50) NOT NULL,
	password VARCHAR(100) NOT NULL,
	email VARCHAR(100) NOT NULL
);

CREATE TABLE BANK_ACCOUNT(
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	user_id BIGINT NOT NULL,
	account_type VARCHAR(50) NOT NULL,
	account_description VARCHAR(255),
	balance BIGINT NOT NULL,
	status VARCHAR(50) NOT NULL
);