package edu.bu.metcs673.trackr.controller;

import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.ControllerAdvice;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.context.request.WebRequest;

import edu.bu.metcs673.trackr.api.GenericApiResponse;
import edu.bu.metcs673.trackr.common.TrackrInputValidationException;

/**
 * Used to handle the custom exceptions that are generated by the application.
 * Returns an error response to the user.
 * 
 * @author Tim Flucker
 *
 */
@ControllerAdvice
public class ExceptionController {

	/**
	 * If a TrackrInputValidationException is thrown, then this block of code will
	 * execute.
	 * 
	 * @param exception
	 * @param request
	 * @return
	 */
	@ExceptionHandler(value = TrackrInputValidationException.class)
	protected ResponseEntity<GenericApiResponse> handleValidationExceptions(TrackrInputValidationException exception,
			WebRequest request) {
		return new ResponseEntity<GenericApiResponse>(GenericApiResponse.errorResponse(exception.getMessage()),
				HttpStatus.BAD_REQUEST);
	}
}
